name: Dev builds (Test)

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  dev:
    uses: nzymedefense/ci/.github/workflows/dev-build.yml@master
    with:
      repo: nzymedefense/nzyme
      ref: ${{ github.sha }}
      branch: ${{ github.ref_name }}
    secrets: inherit
